server:
  port: 8080
spring:
  application:
    name: gateway-test
  cloud:
    zookeeper:
      connect-string: 42.192.49.234:2181
    gateway:
      routes:
      - id: neo_route
        uri: http://www.ityouknow.com
        predicates:
          - Path=/spring-cloud
      - id: rate_filter
        uri: https://www.baidu.com/
        predicates:
          - Path=/test/rate-limit
        filters:
          - name: RateLimit
            args:
              appKey: sss
              qps: 10
