
package webservice.landray.com.landray.kmss.sys.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IEkpWorkflowWebService", targetNamespace = "http://ws.sys.kmss.landray.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IEkpWorkflowWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAuditNotes", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetAuditNotes")
    @ResponseWrapper(localName = "getAuditNotesResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetAuditNotesResponse")
    public String getAuditNotes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getWorkflowDatas", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetWorkflowDatas")
    @ResponseWrapper(localName = "getWorkflowDatasResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetWorkflowDatasResponse")
    public String getWorkflowDatas(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHistoryNodes", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetHistoryNodes")
    @ResponseWrapper(localName = "getHistoryNodesResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetHistoryNodesResponse")
    public String getHistoryNodes(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSysWfUsageList", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetSysWfUsageList")
    @ResponseWrapper(localName = "getSysWfUsageListResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetSysWfUsageListResponse")
    public String getSysWfUsageList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXFormTemplate", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetXFormTemplate")
    @ResponseWrapper(localName = "getXFormTemplateResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetXFormTemplateResponse")
    public String getXFormTemplate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doCommitWorkItem", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.DoCommitWorkItem")
    @ResponseWrapper(localName = "doCommitWorkItemResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.DoCommitWorkItemResponse")
    public String doCommitWorkItem(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNextBranches", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetNextBranches")
    @ResponseWrapper(localName = "getNextBranchesResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetNextBranchesResponse")
    public String getNextBranches(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getXFormContent", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetXFormContent")
    @ResponseWrapper(localName = "getXFormContentResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetXFormContentResponse")
    public String getXFormContent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocProperties", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetDocProperties")
    @ResponseWrapper(localName = "getDocPropertiesResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetDocPropertiesResponse")
    public String getDocProperties(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getYZXFormContent", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetYZXFormContent")
    @ResponseWrapper(localName = "getYZXFormContentResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetYZXFormContentResponse")
    public String getYZXFormContent(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAttachment4String", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetAttachment4String")
    @ResponseWrapper(localName = "getAttachment4StringResponse", targetNamespace = "http://ws.sys.kmss.landray.com/", className = "webservice.landray.com.landray.kmss.sys.ws.GetAttachment4StringResponse")
    public String getAttachment4String(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
